package com.studyinfo.app.data.auth

import android.content.Context
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import com.studyinfo.app.utils.AppResult
import java.security.MessageDigest

/**
 * Google Sign-In via the AndroidX Credential Manager (the modern replacement for the
 * deprecated GoogleSignInClient).
 *
 * Flow: Credential Manager shows the account picker → returns a Google ID token →
 * [GoogleProfile] is handed to [com.studyinfo.app.data.repository.AuthRepository], which
 * creates/links a LOCAL account (offline-first) and best-effort mirrors the token to
 * Firebase Auth so cloud sync works when it is configured.
 *
 * Configuration requirement: the `google-services.json` must contain an OAuth client
 * (the plugin then generates the `default_web_client_id` resource). That entry only
 * exists after the developer, in Firebase Console:
 *   1. enables the Google sign-in provider, and
 *   2. registers this build's SHA-1 fingerprint on the Android app.
 * Until then this object reports "not configured" instead of crashing, and the UI shows
 * a clear explanation.
 */
object GoogleAuth {

    /** Stable identity + profile data extracted from the Google ID token credential. */
    data class GoogleProfile(
        val id: String,          // Google account id ("sub") — stable across devices
        val email: String,
        val displayName: String,
        val photoUrl: String?,
        val idToken: String,     // raw JWT — used for the Firebase mirror
    )

    /**
     * The Web OAuth client id generated by the google-services plugin from
     * google-services.json's `oauth_client` section. Looked up reflectively so the project
     * still compiles when the json has no OAuth clients yet (Google not enabled).
     */
    fun webClientId(context: Context): String? = runCatching {
        val resId = context.resources.getIdentifier(
            "default_web_client_id", "string", context.packageName,
        )
        if (resId != 0) context.getString(resId) else null
    }.getOrNull()?.takeIf { it.isNotBlank() }

    fun isConfigured(context: Context): Boolean = !webClientId(context).isNullOrBlank()

    /**
     * Launch the system account picker and return the chosen Google account.
     *
     * @param activityContext an Activity context (required — the picker is UI).
     */
    suspend fun signIn(activityContext: Context): AppResult<GoogleProfile> {
        val clientId = webClientId(activityContext)
        if (clientId.isNullOrBlank()) {
            return AppResult.failure(
                "Google Sign-In is not configured yet. In Firebase Console: enable the " +
                    "Google provider and add this app's SHA-1 fingerprint, then update " +
                    "app/google-services.json and rebuild.",
            )
        }

        return try {
            val credentialManager = CredentialManager.create(activityContext)
            val googleIdOption = GetGoogleIdOption.Builder()
                .setServerClientId(clientId)
                .setFilterByAuthorizedAccounts(false)   // always show the full account picker
                .build()
            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val response = credentialManager.getCredential(activityContext, request)
            val credential = response.credential
            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val google = GoogleIdTokenCredential.createFrom(credential.data)
                val email = google.email?.trim()?.lowercase().orEmpty()
                if (google.id.isBlank() || google.idToken.isBlank() || email.isBlank()) {
                    AppResult.failure("Google did not return a complete profile. Please try again.")
                } else {
                    AppResult.success(
                        GoogleProfile(
                            id = google.id,
                            email = email,
                            displayName = google.displayName.orEmpty(),
                            photoUrl = google.profilePictureUri?.toString(),
                            idToken = google.idToken,
                        ),
                    )
                }
            } else {
                AppResult.failure("Unexpected sign-in result. Please try again.")
            }
        } catch (e: GetCredentialCancellationException) {
            AppResult.failure("")   // user dismissed the picker — not an error worth showing
        } catch (e: NoCredentialException) {
            AppResult.failure(
                "No Google account is available on this device. Add a Google account in " +
                    "Android Settings → Accounts, then try again.",
            )
        } catch (e: GetCredentialException) {
            AppResult.failure(
                "Google Sign-In failed (${e.type.substringAfterLast('.')}). " +
                    (friendlyHint(e) ?: "Please try again."),
            )
        } catch (e: GoogleIdTokenParsingException) {
            AppResult.failure("Could not read the Google account. Please try again.")
        } catch (e: Exception) {
            AppResult.failure(e.message ?: "Google Sign-In failed. Please try again.")
        }
    }

    /** Called on sign-out so the next sign-in shows the account picker again. */
    suspend fun clearCredentialState(context: Context) {
        runCatching {
            CredentialManager.create(context).clearCredentialState(ClearCredentialStateRequest())
        }
    }

    private fun friendlyHint(e: GetCredentialException): String? = when {
        // Common when the SHA-1 fingerprint of this build isn't registered in Firebase.
        e.message?.contains("DEVELOPER_ERROR", ignoreCase = true) == true ->
            "This build's signature isn't registered in Firebase. Add the app's SHA-1 " +
                "fingerprint in Firebase Console → Project settings → Your apps."
        e.message?.contains("network", ignoreCase = true) == true ->
            "Check your internet connection and try again."
        else -> null
    }

    /** Deterministic local account id for a Google identity (stable across reinstalls). */
    fun localAccountIdFor(googleId: String): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(googleId.toByteArray())
        val hex = digest.joinToString("") { "%02x".format(it) }
        return "google_$hex"
    }
}
